### ISSUE TITLE
Replace the explorers API calls in functions.py with the RequestFromScan class

### ISSUE THREAD

**Issue by sgzerbo** [KarpatkeyDAO/defyes#210]

**Comment by sgzerbo** [comment]
The RequestFromScan class in util/api.py was developed to eventually remove all the explorers APIs constants in constants.py such as API_ETHERSCAN_GETBLOCKNOBYTIME, API_ETHERSCAN_GETBLOCKREWARD, etc.

In particular, the RequestFromScan class is used to fetch the ABI of verified contracts. For this the class currently uses the ImplContractData class in util/impl_contract.py to fetch the ABI of proxy implementations. But this code is incorrect. In functions.py we have the search_proxy_impl_address function which is indeed able to fetch the ABI of proxy implementations. This is the function the RequestFromScan should use

**Comment by ph1t0** [comment]
Added in version: 0.1.0
