### ISSUE TITLE
Replace bare Exception catching by specific ones

### ISSUE THREAD

**Issue by franalbani** [KarpatkeyDAO/defyes#63]
# Progress

- [ ] Aave
- [x] Agave
- [ ] Aura
- [ ] Azuro
- [ ] Balancer
- [ ] Bancor
- [ ] Compound
- [ ] Convex
- [ ] Curve
- [ ] Element
- [ ] Elk
- [ ] Honeyswap
- [ ] Idle
- [ ] IronBank
- [ ] Lido
- [x] Maker
- [ ] mStable
- [ ] Notional
- [ ] QiDao
- [ ] RealT
- [ ] Reflexer
- [ ] SushiSwap
- [ ] Swapr
- [ ] Symmetric
- [ ] UniswapV3
- [x] Unit

**Comment by ph1t0** [comment]
Added in version: 0.1.0
